In [1]:
import numpy as np
## NumPy Creating Arrays
## The array object in NumPy is called ndarray.
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
##Use a tuple to create a NumPy array:
arrTuple  = np.array((1, 2, 3, 4, 5))
print(arrTuple)

[1 2 3 4 5]


In [3]:
##1-D Array
arr_one_D = np.array([1, 2, 3, 4, 5])
##2-D Array

In [4]:
arr_two_D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_two_D)

[[1 2 3]
 [4 5 6]]


#3-D Array

In [5]:
arr_three_D = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr_three_D)
## Dimensions of an array
# Create an array with at least 5 dimensions (ndmin=5 specifies the minimum number of dimensions)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [6]:
arrDim = np.array([1, 2, 3, 4], ndmin=5)

In [7]:
print('arrDim',arrDim)
print('number of dimensions :', arrDim.ndim)

arrDim [[[[[1 2 3 4]]]]]
number of dimensions : 5


In [8]:
#Access 2-D Array Elements
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [9]:
#Access 3-D Array Elements
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [10]:
print('3-D array access: ',arr[0, 1, 2])

3-D array access:  6
