In [1]:
# Multinomial Distribution

# The multinomial distribution is a generalization of the binomial distribution.  
# It describes the outcomes of multiple trials where each trial can result in one of **more than two** possible outcomes.

# In NumPy, we use:
# `np.random.multinomial(n, pvals, size)`
# - `n`: number of trials
# - `pvals`: list of probabilities for each outcome (must sum to 1)
# - `size`: number of samples

In [2]:
import numpy as np

# 100 trials, 3 outcomes with given probabilities
outcomes = np.random.multinomial(n=100, pvals=[0.2, 0.5, 0.3], size=5)

print(outcomes)

[[22 45 33]
 [18 54 28]
 [17 57 26]
 [24 57 19]
 [18 46 36]]
